name: Release Train example for Github Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Set the Release Version
      run: |
        yarn releaseTrain-config --appName=releaseTrain --hookUrl=$SLACK_WEBHOOK_URL --channel=github-actions-example --username=releaseTrain --releaseVersion=$npm_package_version
        echo "#! /bin/bash" >> ./releaseVersion.sh
        echo "releaseVersion=$RELEASE_VERSION" >> ./releaseVersion.sh
        /bin/bash ./scripts/cutRelease.sh
        yarn releaseTrain-notify
      env:
        RELEASE_VERSION: ${{ secrets.RELEASE_VERSION }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: releasetrain
        path: node_modules/releasetrain/**
        retention-days: 30
